# Generated by Django 5.1.3 on 2025-10-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connected', models.BooleanField(default=False)),
                ('ip_address', models.CharField(blank=True, max_length=64)),
                ('last_checkin', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='WifiConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(blank=True, max_length=64)),
                ('password', models.CharField(blank=True, max_length=64)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
