# Generated by Django 5.1.3 on 2025-10-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_devicestatus_wificonfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannedNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(max_length=64)),
                ('rssi', models.IntegerField()),
                ('secure', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
